### ISSUE TITLE
Unable to build wheel with gcc4.7.2

### ISSUE THREAD

**Issue by suhasvirmani** [PyMySQL/mysqlclient#466] opened 2020-12-15 02:57 UTC
Get the following error while running this command
>pip install mysqlclient

Collecting mysqlclient                                                                                                                                                                 
  Downloading mysqlclient-2.0.2.tar.gz (88 kB)                                                                                                                                         
     |████████████████████████████████| 88 kB 15.4 MB/s                                                                                                                                
Building wheels for collected packages: mysqlclient                                                                                                                                    
  Building wheel for mysqlclient (setup.py) ... error                                                                                                                                  
  ERROR: Command errored out with exit status 1:                                                                                                                                       
   command: venv/bin/python3.7.4 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-tumh91mw/mysqlclient_c48fccb62cf84d25a6249be1d8df8c94/setup.py'"'"'; __file__='"'"'/tmp/pip-install-tumh91mw/mysqlclient_c48fccb62cf84d25a6249be1d8df8c94/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-in2kmamb                                                                                                                                                                                 
       cwd: /tmp/pip-install-tumh91mw/mysqlclient_c48fccb62cf84d25a6249be1d8df8c94/                                                                                                    
  Complete output (29 lines):                                                                                                                                                          
  running bdist_wheel                                                                                                                                                                  
  running build                                                                                                                                                                        
  running build_py                                                                                                                                                                     
  creating build                                                                                                                                                                       
  creating build/lib.linux-x86_64-3.7                                                                                                                                                  
  creating build/lib.linux-x86_64-3.7/MySQLdb                                                                                                                                          
  copying MySQLdb/__init__.py -> build/lib.linux-x86_64-3.7/MySQLdb                                                                                                                    
  copying MySQLdb/_exceptions.py -> build/lib.linux-x86_64-3.7/MySQLdb                                                                                                                 
  copying MySQLdb/connections.py -> build/lib.linux-x86_64-3.7/MySQLdb                                                                                                                 
  copying MySQLdb/converters.py -> build/lib.linux-x86_64-3.7/MySQLdb                                                                                                                  
  copying MySQLdb/cursors.py -> build/lib.linux-x86_64-3.7/MySQLdb                                                                                                                     
  copying MySQLdb/release.py -> build/lib.linux-x86_64-3.7/MySQLdb                                                                                                                     
  copying MySQLdb/times.py -> build/lib.linux-x86_64-3.7/MySQLdb                                                                                                                       
  creating build/lib.linux-x86_64-3.7/MySQLdb/constants                                                                                                                                
  copying MySQLdb/constants/__init__.py -> build/lib.linux-x86_64-3.7/MySQLdb/constants                                                                                                
  copying MySQLdb/constants/CLIENT.py -> build/lib.linux-x86_64-3.7/MySQLdb/constants                                                                                                  
  copying MySQLdb/constants/CR.py -> build/lib.linux-x86_64-3.7/MySQLdb/constants                                                                                                      
  copying MySQLdb/constants/ER.py -> build/lib.linux-x86_64-3.7/MySQLdb/constants                                                                                                      
  copying MySQLdb/constants/FIELD_TYPE.py -> build/lib.linux-x86_64-3.7/MySQLdb/constants                                                                                              
  copying MySQLdb/constants/FLAG.py -> build/lib.linux-x86_64-3.7/MySQLdb/constants                                                                                                    
  running build_ext                                                                                                                                                                    
  building 'MySQLdb._mysql' extension                                                                                                                                                  
  creating build/temp.linux-x86_64-3.7                                                                                                                                                 
  creating build/temp.linux-x86_64-3.7/MySQLdb                                                                                                                                         
  /usr/pkgs/gcc/4.7.2/bin/gcc -O2 -fPIC -I/usr/intel/pkgs/python3/3.7.4/include -L/usr/pkgs/python3/3.7.4/lib64 -L/usr/pkgs/python3/3.7.4/lib -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -O3 -Wall -fPIC -Dversion_info=(2,0,2,'final',0) -D__version__=2.0.2 -I/usr/pkgs/mysql/5.7.16/include -I/usr/pkgs/python3/3.7.4/include/python3.7m -c MySQLdb/_mysql.c -o build/temp.linux-x86_64-3.7/MySQLdb/_mysql.o -fabi-version=2 -fno-omit-frame-pointer                                                                    
  MySQLdb/_mysql.c: In function ‘_mysql_row_to_dict_cached’:                                                                                                                           
  MySQLdb/_mysql.c:1340:5: error: ‘for’ loop initial declarations are only allowed in C99 mode                                                                                         
  MySQLdb/_mysql.c:1340:5: note: use option -std=c99 or -std=gnu99 to compile your code                                                                                                
  error: command '/usr/intel/pkgs/gcc/4.7.2/bin/gcc' failed with exit status 1                                                                                                         
  ----------------------------------------                                                                                                                                             
  ERROR: Failed building wheel for mysqlclient                                                                                                                                         
  Running setup.py clean for mysqlclient                                                                                                                                               
Failed to build mysqlclient                                                                                                                                                            
Installing collected packages: mysqlclient                                                                                                                                             
    Running setup.py install for mysqlclient ... error                                                                                                                                 
    ERROR: Command errored out with exit status 1:                                                                                                                                     
     command: venv/bin/python3.7.4 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-tumh91mw/mysqlclient_c48fccb62cf84d25a6249be1d8df8c94/setup.py'"'"'; __file__='"'"'/tmp/pip-install-tumh91mw/mysqlclient_c48fccb62cf84d25a6249be1d8df8c94/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-m1kosg_l/install-record.txt --single-version-externally-managed --compile --install-headers venv/include/site/python3.7/mysqlclient                                                                                                                                                          
         cwd: /tmp/pip-install-tumh91mw/mysqlclient_c48fccb62cf84d25a6249be1d8df8c94/                                                                                                  
    Complete output (29 lines):                                                                                                                                                        
    running install                                                                                                                                                                    
    running build                                                                                                                                                                      
    running build_py                                                                                                                                                                   
    creating build                                                                                                                                                                     
    creating build/lib.linux-x86_64-3.7                                                                                                                                                
    creating build/lib.linux-x86_64-3.7/MySQLdb                                                                                                                                        
    copying MySQLdb/__init__.py -> build/lib.linux-x86_64-3.7/MySQLdb                                                                                                                  
    copying MySQLdb/_exceptions.py -> build/lib.linux-x86_64-3.7/MySQLdb                                                                                                               
    copying MySQLdb/connections.py -> build/lib.linux-x86_64-3.7/MySQLdb                                                                                                               
    copying MySQLdb/converters.py -> build/lib.linux-x86_64-3.7/MySQLdb                                                                                                                
    copying MySQLdb/cursors.py -> build/lib.linux-x86_64-3.7/MySQLdb                                                                                                                   
    copying MySQLdb/release.py -> build/lib.linux-x86_64-3.7/MySQLdb                                                                                                                   
    copying MySQLdb/times.py -> build/lib.linux-x86_64-3.7/MySQLdb                                                                                                                     
    creating build/lib.linux-x86_64-3.7/MySQLdb/constants                                                                                                                              
    copying MySQLdb/constants/__init__.py -> build/lib.linux-x86_64-3.7/MySQLdb/constants                                                                                              
    copying MySQLdb/constants/CLIENT.py -> build/lib.linux-x86_64-3.7/MySQLdb/constants                                                                                                
    copying MySQLdb/constants/CR.py -> build/lib.linux-x86_64-3.7/MySQLdb/constants                                                                                                    
    copying MySQLdb/constants/ER.py -> build/lib.linux-x86_64-3.7/MySQLdb/constants                                                                                                    
    copying MySQLdb/constants/FIELD_TYPE.py -> build/lib.linux-x86_64-3.7/MySQLdb/constants                                                                                            
    copying MySQLdb/constants/FLAG.py -> build/lib.linux-x86_64-3.7/MySQLdb/constants                                                                                                  
    running build_ext                                                                                                                                                                  
    building 'MySQLdb._mysql' extension                                                                                                                                                
    creating build/temp.linux-x86_64-3.7                                                                                                                                               
    creating build/temp.linux-x86_64-3.7/MySQLdb                                                                                                                                       
    gcc/4.7.2/bin/gcc -O2 -fPIC -Ipython3/3.7.4/include -Lpython3/3.7.4/lib64 -Lpython3/3.7.4/lib -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -O3 -Wall -fPIC -Dversion_info=(2,0,2,'final',0) -D__version__=2.0.2 -I/usr/pkgs/mysql/5.7.16/include -Ipython3/3.7.4/include/python3.7m -c MySQLdb/_mysql.c -o build/temp.linux-x86_64-3.7/MySQLdb/_mysql.o -fabi-version=2 -fno-omit-frame-pointer                                                                  
    MySQLdb/_mysql.c: In function ‘_mysql_row_to_dict_cached’:                                                                                                                         
    MySQLdb/_mysql.c:1340:5: error: ‘for’ loop initial declarations are only allowed in C99 mode                                                                                       
    MySQLdb/_mysql.c:1340:5: note: use option -std=c99 or -std=gnu99 to compile your code                                                                                              
    error: command 'gcc/4.7.2/bin/gcc' failed with exit status 1                                                                                                       
    ----------------------------------------                                                                                                                                           
ERROR: Command errored out with exit status 1: venv/bin/python3.7.4 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-tumh91mw/mysqlclient_c48fccb62cf84d25a6249be1d8df8c94/setup.py'"'"'; __file__='"'"'/tmp/pip-install-tumh91mw/mysqlclient_c48fccb62cf84d25a6249be1d8df8c94/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-m1kosg_l/install-record.txt --single-version-externally-managed --compile --install-headers venv/include/site/python3.7/mysqlclient Check the logs for full command output.

**Comment by methane** [comment] 2020-12-15 03:50
Duplicate of #460.
See https://github.com/PyMySQL/mysqlclient/issues/460#issuecomment-742512850 too.

**Closed by methane** 2020-12-15 03:50 UTC
