### ISSUE TITLE
None instead of SQL in django debug mode

### ISSUE THREAD

**Issue by adibalcan** [PyMySQL/mysqlclient#525] opened 2022-01-17 11:39 UTC
### Describe the bug

I receive None instead of SQL when using mysqlclient==2.0.3 

I don't have the same problem in mysqlclient==2.1.0 but here I receive KeyError: <class 'bytes'> at line 266, in get_new_connection
conn.encoders[SafeBytes] = conn.encoders[bytes]

So I can't use any version

### Environment

**MySQL Server**

MySQL 5.7

**MySQL Client**

MacOSX 12.1
Python 3.7

### Additional context
Django 1.9

**Comment by methane** [comment] 2022-01-17 14:08
"receive None instead of SQL" doesn't make sense at all.
And there is no complete step to reproduce.
I just close this, because I am not free tech support.

**Closed by methane** 2022-01-17 14:08 UTC
