### ISSUE TITLE
Latest version 2.0.2 has issues on RHEL

### ISSUE THREAD

**Issue by yashodhan10** [PyMySQL/mysqlclient#461] opened 2020-12-10 15:07 UTC
### Read this first

We don't use this issue tracker to help users.  If you had trouble, please ask it on some user community. See [here](https://github.com/PyMySQL/mysqlclient-python#support).
Please use this tracker only when you are sure about it is an issue of this software.

And please provide full information from first.  I don't want to ask questions like "What is your Python version?", "Do you confirm MySQL error log?".  If the issue report looks incomplete, I will just close it.

Are you ready?  Please remove until here and make a good issue report!!

### Describe the bug

Latest version 2.0.2 fails to install. 

pip3 install mysqlclient
Collecting mysqlclient
  Downloading https://files.pythonhosted.org/packages/0e/68/f79de0e0fcdb041783124b825771e0ba6a3d0893b7b4c4735f130e42af47/mysqlclient-2.0.2.tar.gz (88kB)
    100% |████████████████████████████████| 92kB 2.8MB/s
Installing collected packages: mysqlclient
  Running setup.py install for mysqlclient ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-0w54c7pa/mysqlclient/setup.py';f=getattr(token
ize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-d19wsaur-record/
install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/MySQLdb
    copying MySQLdb/__init__.py -> build/lib.linux-x86_64-3.6/MySQLdb
    copying MySQLdb/_exceptions.py -> build/lib.linux-x86_64-3.6/MySQLdb
    copying MySQLdb/connections.py -> build/lib.linux-x86_64-3.6/MySQLdb
    copying MySQLdb/converters.py -> build/lib.linux-x86_64-3.6/MySQLdb
    copying MySQLdb/cursors.py -> build/lib.linux-x86_64-3.6/MySQLdb
    copying MySQLdb/release.py -> build/lib.linux-x86_64-3.6/MySQLdb
    copying MySQLdb/times.py -> build/lib.linux-x86_64-3.6/MySQLdb
    creating build/lib.linux-x86_64-3.6/MySQLdb/constants
    copying MySQLdb/constants/__init__.py -> build/lib.linux-x86_64-3.6/MySQLdb/constants
    copying MySQLdb/constants/CLIENT.py -> build/lib.linux-x86_64-3.6/MySQLdb/constants
    copying MySQLdb/constants/CR.py -> build/lib.linux-x86_64-3.6/MySQLdb/constants
    copying MySQLdb/constants/ER.py -> build/lib.linux-x86_64-3.6/MySQLdb/constants
    copying MySQLdb/constants/FIELD_TYPE.py -> build/lib.linux-x86_64-3.6/MySQLdb/constants
    copying MySQLdb/constants/FLAG.py -> build/lib.linux-x86_64-3.6/MySQLdb/constants
    running build_ext
    building 'MySQLdb._mysql' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/MySQLdb
    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Dversion_info=(2,0,2,'final',0) -D__version__=2.0.2 -I/usr/include/mysql -I/usr/include/python3.6m -c MySQLdb/_mysql.c -o build/temp.linux-x86_64-3.6/MySQLdb/_mysql.o -g -m64 -fPIC -g -fabi-version=2 -fno-omit-frame-pointer -fno-strict-aliasing
    MySQLdb/_mysql.c: In function ‘_mysql_row_to_dict_cached’:
    MySQLdb/_mysql.c:1340:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
         for (unsigned int i=0; i<n; i++) {
         ^
    MySQLdb/_mysql.c:1340:5: note: use option -std=c99 or -std=gnu99 to compile your code
    error: command 'gcc' failed with exit status 1

### To Reproduce

**Schema**

```
create table ....
```

**Code**

```py
con = MySQLdb.connect(...)
cur = con.cursor()
cur.execute(...)
```

### Environment

**MySQL Server**

- Server OS (e.g. Windows 10, Ubuntu 20.04): Red Hat
- Server Version (e.g. MariaDB 10.3.16): 7.6

**MySQL Client**

- OS (e.g. Windows 10, Ubuntu 20.04):

- Python (e.g. Homebrew Python 3.7.5):

- Connector/C (e.g. Homebrew mysql-client 8.0.18):

**Comment by methane** [comment] 2020-12-11 02:49
Duplicate of #460.

**Closed by methane** 2020-12-11 02:49 UTC
