### ISSUE TITLE
Version 2.0.2 has install issue with centos 7 

### ISSUE THREAD

**Issue by avisual** [PyMySQL/mysqlclient#460] opened 2020-12-10 12:09 UTC
MySQLdb/_mysql.c: In function ‘_mysql_row_to_dict_cached’:
    MySQLdb/_mysql.c:1340:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
         for (unsigned int i=0; i<n; i++) {
         ^
    MySQLdb/_mysql.c:1340:5: note: use option -std=c99 or -std=gnu99 to compile your code
    error: command 'gcc' failed with exit status 1

rolling back to 2.0.1 works

**Comment by methane** [comment] 2020-12-10 13:13
Try `export CFLAGS="-std=c99"`

**Comment by dwt** [comment] 2020-12-10 15:05
Same problem here.

@methane that will likely be a workaround, but should be fixed somewhere in https://github.com/PyMySQL/mysqlclient/blob/master/setup_posix.py as far as I can. tell.

**Comment by dwt** [comment] 2020-12-10 15:59
Can confirm `CFLAGS="-std=c99" pip install mysqlclient` works as a workaround.

Not sure how I would apply that via a requirements.txt file, so I've constrained to the previous version which is ok.

**Comment by boagg** [comment] 2020-12-11 11:27
Hi, same problem here with debian Jessie (Yeah we have some servers work with a oldoldstable.. :/ We work on it !)

Meanwhile, CFLAGS="-std=c99" works as a workaround too.

**Comment by bac** [comment] 2020-12-11 12:31
https://github.com/PyMySQL/mysqlclient/pull/455 Reverts the Maria version and should solve this issue. 2.0.3 needs to be released.

**Comment by nyashabryan** [comment] 2020-12-11 12:37
@methane error on Centos7 with gcc~4.8.5 comes from this [commit ](https://github.com/PyMySQL/mysqlclient/commit/1731d273410909ef8efe1188d98e3fcd9d274144). The solution is either to refactor method or add the CFLAG="-std=99".

**Comment by methane** [comment] 2020-12-12 01:55
> error on Centos7 with gcc~4.8.5 comes from this [commit ](https://github.com/PyMySQL/mysqlclient/commit/1731d273410909ef8efe1188d98e3fcd9d274144).

Thanks. I know it of course. I just don't have time to create new release.

> The solution is either to refactor method

Rewriting code from C99 to C89 is not "refactoring". As you know, it's 2020 already.

> or add the CFLAG="-std=99".

I know it of course. Everyone who can understand compiler error know it.

And all CentOS user should know it too and expect this kind of errors when using new OSS softwares on old CentOS.

Many OSS use recent Ubuntu LTS for CI. And CentOS users chose "self support" instead of paying red hat supoprt.
So CentOS users should expect and all troubles caused by running new software on old platform, and can fix them by themselves.

If you think this trouble is serious, I recommend you to switch to Ubuntu TLS. Ubuntu is the default OS for OSS CIs (Github Actions, Travis-CI, and so on). Or you can use RHEL for paid support.
CentOS is going to die except CentOS Stream. https://blog.centos.org/2020/12/future-is-centos-stream/ .

**Comment by dwt** [comment] 2020-12-12 11:29
@methane Not sure I'm getting what you are proposing. Do you imply that the setting `--std=c99` should not be handed to the compiler, even though the project is written in it?

**Comment by methane** [comment] 2020-12-12 11:51
What I'm proposing is to stop sending more "me too" message or any other advices. All comments in this thread are just spam to me.

**Closed** 2021-01-01 01:24 UTC
