### ISSUE TITLE
Bytes function TypeError: string argument without an encoding

### ISSUE THREAD

**Issue by adigeo** [PyMySQL/mysqlclient#454] opened 2020-12-06 12:04 UTC
### Describe the bug

In https://github.com/PyMySQL/mysqlclient-python/blob/master/MySQLdb/__init__.py

```
def Binary(x):
    return bytes(x)

```

### To Reproduce

**Schema**

Any

**Code**

When the Binary function is called with a string argument it will fail:
 
```
>>> s = 'abcd'
>>> bytes(s)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: string argument without an encoding
```

### Environment

**MySQL Server**

Any

**MySQL Client**

Any

**Comment by SuperVirus** [comment] 2020-12-06 13:11
Hi,
there are many different encodings like ASCII, ISO-8859-1, UTF-8, UTF-16 - only to name e few of them.
So Python does not know how to convert a string to bytes, as every encoding has a different binary representation of the same string.

But there is a away to tell Python, what encoding should be used:
```python
# Encode string s to UTF-8 bytes:
b = s.encode(encoding='utf-8')

# Decode UTF-8 bytes to string
s = b.decode(encoding='utf-8')
```

Here are examples for different common encodings:
```python
>>> s = 'foobar ä'
>>> s.encode('utf-8')
b'foobar \xc3\xa4'
>>> s.encode('utf-16')
b'\xff\xfef\x00o\x00o\x00b\x00a\x00r\x00 \x00\xe4\x00'
>>> s.encode('iso-8859-1')
b'foobar \xe4'
>>> s.encode('cp437')
b'foobar \x84'
>>> s.encode('ascii')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'ascii' codec can't encode character '\xe4' in position 7: ordinal not in range(128)
```
As you can see, every encoding result in a different binary representation - encoding to ASCII even fails, as there is no 'ä' defined...

**Comment by methane** [comment] 2020-12-07 07:12
Duplicate of #444.

**Closed by methane** 2020-12-07 07:12 UTC
